### ISSUE TITLE
Problem the choice of y target in the adversarial model

### ISSUE THREAD

**Issue by JiaxiangBU** [dylan-slack/Fooling-LIME-SHAP#10]
Will the the both model, the biased original model and adversarial one return the same the prediction for a test real sample?

https://github.com/dylan-slack/Fooling-LIME-SHAP/blob/633d7f8c87d509765619c61ace7838f8a7ce9505/adversarial_models.py#L156-L162

Here the y label is set as whether the sample is real or synthesized. With the different target definition, I am confused the both two model return the same prediction values.

**Comment by dylan-slack** [comment]
The y is set here to train a model that tells apart synthesized + real data.

This model is a separate model than the biased + innocuous models. It’s used to determine whether to predict with the biased or adversarial model, which may or may not make the same predictions.

**Comment by JiaxiangBU** [comment]
> This model is a separate model than the biased + innocuous models. It’s used to determine whether to predict with the biased or adversarial model, which may or may not make the same predictions.


Here the data augmentation method  makes the bias feature ranking lower by adding the noise to the bias feature.

Thus, the adversarial model uses the synthesized feature and real target to produce a fake SHAP ranking summary plot, which lies to the audience.

The separate model only plays a role that the separate model cannot figure out whether the sample is from the real dataset or synthesized ones

Do I make a **correct illustration** the idea of the separate model?
